#!/bin/bash -e

export PREFIX="poetry run"
export SOURCE_FILES="app"

set -x

${PREFIX} flake8 $SOURCE_FILES --ignore=E501
${PREFIX} black --check --diff --target-version=py38 $SOURCE_FILES
${PREFIX} mypy $SOURCE_FILES